unit Images;

interface

type

  { TImages }

  TImages = class
  public
    const ADD = 0;
    const APPLICATION_XP_TERMINAL = 1;
    const ARROW_REFRESH = 2;
    const ARROW_SWITCH_BLUE = 3;
    const ARROW_UNDO = 4;
    const BIN = 5;
    const BOOK_OPEN = 6;
    const BRICKS = 7;
    const BRICKS_ADD = 8;
    const BRICKS_COG = 9;
    const BRICKS_DELETE = 10;
    const BUG = 11;
    const BULLET_DOWN = 12;
    const BULLET_UP = 13;
    const COG = 14;
    const COG_GO = 15;
    const CONNECT = 16;
    const CONNECT_SECURE = 17;
    const CROSS = 18;
    const CUT = 19;
    const DECLINE = 20;
    const DECLINE_ADD = 21;
    const DECLINE_SELECT = 22;
    const DECLINE_TRANSMIT_ADD = 23;
    const DELETE = 24;
    const DISCONNECT = 25;
    const DISK = 26;
    const DOOR_OUT = 27;
    const DRIVE = 28;
    const DRIVE_GO = 29;
    const DRIVE_SELECT = 30;
    const EQUALIZER_HIGH = 31;
    const ERASE = 32;
    const ERROR = 33;
    const EXCLAMATION = 34;
    const FADE_IN = 35;
    const FADE_OUT = 36;
    const FIND = 37;
    const FOLDER_BRICKS = 38;
    const FOLDER_EXPLORE = 39;
    const FOLDER_GO = 40;
    const FOLDER_IN = 41;
    const FOLDER_MUSIC = 42;
    const FOLDER_TRANSMIT = 43;
    const FOLDER_TRANSMIT_ADD = 44;
    const FOLDER_TRANSMIT_PLAY = 45;
    const FOLDER_TRANSMIT_RECORD = 46;
    const FOLDER_TRANSMIT_RECORD_PLAY = 47;
    const FONT = 48;
    const FONT_GROUP = 49;
    const FONT_USER = 50;
    const GROUP = 51;
    const HEART = 52;
    const HELP = 53;
    const INFORMATION = 54;
    const KEYBOARD = 55;
    const LIGHTNING = 56;
    const LINES_COMBINED = 57;
    const LINE_END = 58;
    const LINE_PLAY = 59;
    const LINE_START = 60;
    const LINK_GO = 61;
    const LOCK = 62;
    const MUSIC = 63;
    const MUSIC_IN = 64;
    const MUSIC_INFORMATION = 65;
    const NEXT_BLUE = 66;
    const PACKAGE_DOWN = 67;
    const PAGE_WHITE_COPY = 68;
    const PAGE_WHITE_MUSIC_OUT = 69;
    const PAGE_WHITE_TRANSMIT = 70;
    const PAGE_WHITE_TRANSMIT_ADD = 71;
    const PAINT = 72;
    const PAUSE_BLUE = 73;
    const PLAY_BLUE = 74;
    const PLAY_END_BLUE = 75;
    const PLAY_GO = 76;
    const PLUGIN = 77;
    const PREVIOUS_BLUE = 78;
    const RECORD_PAUSE = 79;
    const RECORD_PLAY = 80;
    const RECORD_RED = 81;
    const RECORD_RED_COG = 82;
    const RESULTSET_NEXT = 83;
    const RESULTSET_PREVIOUS = 84;
    const SCRIPT_BRICKS = 85;
    const SCRIPT_BRICKS_ADD = 86;
    const SCRIPT_BRICKS_DELETE = 87;
    const SCRIPT_DECLINE = 88;
    const SCRIPT_DECLINE_ADD = 89;
    const SCRIPT_DECLINE_DELETE = 90;
    const SCRIPT_EDIT = 91;
    const SCRIPT_HEART = 92;
    const SCRIPT_HEART_ADD = 93;
    const SCRIPT_HEART_DELETE = 94;
    const SCRIPT_IN = 95;
    const SCRIPT_OUT = 96;
    const SCRIPT_USER_GRAY_COOL = 97;
    const SCRIPT_USER_GRAY_COOL_ADD = 98;
    const SOUND = 99;
    const SOUND_LOW = 100;
    const SOUND_MUTE = 101;
    const STAR = 102;
    const STAR_2 = 103;
    const STAR_3 = 104;
    const STAR_4 = 105;
    const STAR_5 = 106;
    const STAR_BLUE = 107;
    const STAR_BLUE_2 = 108;
    const STAR_BLUE_3 = 109;
    const STAR_BLUE_4 = 110;
    const STAR_BLUE_5 = 111;
    const STOP_BLUE = 112;
    const STOP_RED = 113;
    const STOP_RED_MUSIC = 114;
    const TAG_BLUE_EDIT = 115;
    const TAG_GREEN = 116;
    const TEXTFIELD_RENAME = 117;
    const TEXTFIELD_RENAME_COG = 118;
    const TICK = 119;
    const TIME = 120;
    const TIMELINE_MARKER = 121;
    const TRANSMIT = 122;
    const TRANSMIT_ADD = 123;
    const TRANSMIT_EDIT = 124;
    const USER = 125;
    const USER_GO = 126;
    const USER_GRAY_COOL = 127;
    const USER_GRAY_COOL_ADD = 128;
    const USER_LEAVE = 129;
    const WAND = 130;
    const WRENCH_APPLICATION = 131;
    const WRENCH_BRICKS = 132;
    const WRENCH_TRANSMIT = 133;
    const ZOOM_IN = 134;
    const ZOOM_OUT = 135;
  end;

implementation

end.

